server:
  port: 8080

spring:
  application:
    name: api-gateway-server

  cloud:
    gateway:
      routes:
        - id: user-auth-service
          uri: lb://user-auth-service
          predicates:
            - Path=/user-auth-service/**
        - id: fundraiser-service
          uri: lb://fundraiser-service
          predicates:
            - Path=/fundraiser-service/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
